workdir:
  /path/to/workdir/output
container:
  docker://naotokubota/shiba:v1.0.0
gtf:
  /path/to/workdir/annotation.gtf
experiment_table:
  /path/to/workdir/Shiba_experiment.tsv

# Tosa single-cell counting from BAM/CRAM
minimum_anchor_length:
  8
boundary_anchor_length:
  1
minimum_intron_length:
  20
maximum_intron_length:
  500000
strand:
  unstranded

# PSI calculation
only_psi:
  False
fdr:
  0.05
delta_psi:
  0.1
reference_group:
  Cluster-1
alternative_group:
  Cluster-2
minimum_reads:
  10
beta_binomial:
  False
excel:
  False
