name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ['bug🐞']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before you submit a bug report, please run shiba with `--verbose` to get more detailed logs.

  - type: textarea
    id: description
    attributes:
      label: '📋 Description'
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: input
    id: shiba_version
    attributes:
      label: '🔖 Shiba Version'
      description: 'Required: Specify the Shiba version you are using. You can find this information in the `shiba.py -h` command.'
      placeholder: 'e.g., v0.6.2'
    validations:
      required: true

  - type: textarea
    attributes:
      label: '⚠️ Error message'
      description: |
        Optional: If applicable, add the error message here.
    validations:
      required: false

  - type: textarea
    id: experiment_table
    attributes:
      label: '🧪 Experiment Table'
      description: 'Optional: Copy and paste the experiment table that you are using.'
    validations:
      required: false

  - type: textarea
    id: config_yaml
    attributes:
      label: '📄 Config YAML'
      description: 'Optional: Copy and paste the config YAML that you are using.'
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: '🔍 Environment'
      description: |
          Optional: The environment information.
          Example:
          OS: WSL (Ubuntu 22.04)
      value: |
          OS:
      render: markdown
    validations:
      required: false

  - type: textarea
    id: anything_else
    attributes:
      label: '📎 Anything else?'
      description: |
        Optional: Add any other contexts, links, or screenshots about the bug here.
    validations:
      required: false
