name: 💡 Feature Request
description: Suggest an idea for this project
title: '[Feature Request]: '
labels: ['request💡']

body:
  - type: textarea
    id: description
    attributes:
      label: '📋 Description'
      description: A clear and concise description of the request.
    validations:
      required: true

  - type: input
    id: shiba_version
    attributes:
      label: '🔖 Shiba Version'
      description: 'Required: Specify the Shiba version you are using. You can find this information in the `python shiba.py -h` command.'
      placeholder: 'e.g., v0.6.0'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: '🔍 Environment'
      description: |
          Optional: The environment information.
          Example:
          OS: WSL (Ubuntu 22.04)
      value: |
          OS:
      render: markdown
    validations:
      required: false


  - type: textarea
    id: anything_else
    attributes:
      label: '📎 Anything else?'
      description: |
        Optional: Add any other contexts, links, or screenshots about the feature request here.
    validations:
      required: false
