###############################################################
# Dockerfile to build container images for Shiba development
# Based on mambaorg/micromamba:2.5
################################################################

FROM mambaorg/micromamba:2.5

# File Author / Maintainer
LABEL maintainer="Naoto Kubota <naotok@ucr.edu>"

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=/opt/conda/bin:$PATH

USER root

# Install dependencies first
RUN apt-get -qq update && \
	apt-get -qq -y install \
    build-essential gcc g++ make cmake libtool texinfo dpkg-dev pkg-config \
    libgsl-dev wget locate less vim zlib1g-dev bzip2 lzma curl git r-base \
    libboost-dev libcurl4-openssl-dev libboost-all-dev libbz2-dev liblzma-dev \
    libpcre2-dev

# Tosa is installed from crates.io until its Bioconda package is available.
RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal && \
    /root/.cargo/bin/cargo install tosa --version 1.0.0 --locked && \
    install /root/.cargo/bin/tosa /opt/conda/bin/tosa && \
    rm -rf /root/.cargo /root/.rustup

USER $MAMBA_USER

# Install shiba with micromamba
RUN micromamba install -y -n base -c conda-forge -c bioconda -c defaults shiba r-glmmtmb r-jsonlite

# Install styleframe
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN pip install --upgrade pip && \
    pip install styleframe==4.2

# Install shiba2sashimi
RUN pip install shiba2sashimi

# Install the checked-out Shiba source
USER root
COPY . /opt/Shiba
RUN ln -sf /opt/Shiba/shiba.py /opt/conda/bin/shiba.py && \
	ln -sf /opt/Shiba/scshiba.py /opt/conda/bin/scshiba.py
USER $MAMBA_USER

# Set working directory
WORKDIR /home

# bash
CMD ["bash"]
