name: Create Release and Build Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions: write-all

jobs:
  create-release-and-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        id: tag_version
        run: |
          NEW_TAG=$(cat VERSION)
          echo "New tag is $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a ${{ steps.tag_version.outputs.NEW_TAG }} -m "Release ${{ steps.tag_version.outputs.NEW_TAG }}"
          git push origin ${{ steps.tag_version.outputs.NEW_TAG }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.NEW_TAG }}
          name: ${{ steps.tag_version.outputs.NEW_TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          TAG=${{ steps.tag_version.outputs.NEW_TAG }}
          docker build -t naotokubota/shiba:$TAG -t naotokubota/shiba:latest -f docker/Dockerfile .
          docker push naotokubota/shiba:$TAG
          docker push naotokubota/shiba:latest
